In [1]:
print("hello world")

hello world


# NUMPY ---


In [2]:
import numpy as np   #import statement


In [44]:
a = np.array([[1,2,3],[4,5,6]])

b = a.reshape(3,2)

b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
b.ndim

2

In [67]:
#create Array
arr = np.array([[12,34,67,88,99,9],[1,2,3,4,5,6]])
print(arr)
print(arr.ndim)

[[12 34 67 88 99  9]
 [ 1  2  3  4  5  6]]
2


In [81]:
b = np.expand_dims(a2,axis=1)
print(b)
print(b.ndim)

[[[[[[[[[[12 34 67 88 99  9]
         [ 1  2  3  4  5  6]]]]]]]]]]
10


In [82]:
a2 = b[np.newaxis, :]
print(a2)
a2.ndim

[[[[[[[[[[[12 34 67 88 99  9]
          [ 1  2  3  4  5  6]]]]]]]]]]]


11

In [109]:
print(arr)

[[12 34 67 88 99  9]
 [ 1  2  3  4  5  6]]


In [121]:
arr[:1:,1]

array([34])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
n = np.arange(0,10,3)
print(n)
n[::-1]

[0 3 6 9]


array([9, 6, 3, 0])

In [135]:
# np.linspace():create equally space  value # linear space elements in a range.

arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# creating arr with zeros
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [137]:
# creating array with 1's
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [139]:
# create an array with full of specific values

arr = np.full((5,3),9)
arr

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [154]:
random_int_array_1d = np.random.randint(0, 10, 5)
random_int_array_1d


array([1, 5, 7, 0, 6])

In [147]:
random_int_array_2d = np.random.randint(5, 20, size=(3, 4))
random_int_array_2d

array([[ 8,  9, 18,  5],
       [ 8, 18, 16,  9],
       [ 9, 13, 11, 16]])

In [12]:
# creating identity matrix : used in linear algebra.
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [143]:
# creates random numbers between 0 and 1
arr = np.random.rand(5)
arr

array([0.64800787, 0.8003701 , 0.81642698, 0.09066271, 0.08671561])

Attributes :
  - ndim : returns number of dimension in array
  - shape - retuns shpae and column as tuple
  - size it returns total number if elements
  - dtype : returns the datatype of elements

In [14]:
arr = np.array([ [1,2,3],[4,5,6]])
arr
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [15]:
arr = np.array([ [1,2,2,3],[1,4,5,6]]) # homogenous data
arr
# print(arr.ndim)
# print(arr.shape)
# print(arr.size)
# print(arr.dtype)

array([[1, 2, 2, 3],
       [1, 4, 5, 6]])

In [16]:
arr = np.array([[1,2,3,4],[0,9,8,7],[2,3,4,5]])
print(arr)

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

array1 = arr.reshape(3,4)
arr

[[1 2 3 4]
 [0 9 8 7]
 [2 3 4 5]]
2
(3, 4)
12
int64


array([[1, 2, 3, 4],
       [0, 9, 8, 7],
       [2, 3, 4, 5]])

In [17]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
arr = np.linspace(2,3,10)
arr

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [19]:
arr = np.arange(1,30)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
# flattening a multi-dimensional array into 1D.
arr2 = np.array([[1,2],[2,3]])
print(arr2)
arr1 = arr2.ravel()
arr1

[[1 2]
 [2 3]]


array([1, 2, 2, 3])

In [21]:
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
arr1 = arr.reshape(3,4)  # reshaping an array.
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
# convert array into 1d, often returns copy
arr = np.array([[1,2],[3,4]])
#print(arr)
flat = arr.flatten()
print(flat)

[1 2 3 4]


In [24]:
# transpose of an array.
arr = np.array([[1,2,1],[1,3,4]])
print(arr)
print("---------")
print(arr.T)

[[1 2 1]
 [1 3 4]]
---------
[[1 1]
 [2 3]
 [1 4]]


In [25]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[:])
print(arr[2:4])

10
50
[10 20 30 40 50]
[30 40]


In [26]:
arr = np.array([[1,2,3],[3,4,5],[5,6,7]])
# print(arr[0][0])
# print(arr[0,0])
# print(arr[:1])
# print(arr[:,0]) # column wise

# print(arr[:,-1])

print(arr[1:,1:])

print(arr[1:,0:])

[[4 5]
 [6 7]]
[[3 4 5]
 [5 6 7]]


In [27]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]


In [28]:
print(arr[0,1])

2


In [29]:
print(arr[:,-1])

[4 8 5 1]


In [30]:
print(arr[-1:,])

[[4 3 2 1]]


In [31]:
print(arr[1:,:-1])

[[5 6 7]
 [8 7 6]
 [4 3 2]]


In [32]:
print(arr[2:,1:3])

[[7 6]
 [3 2]]


# Operations on Array

In [157]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]


In [160]:
arr1 = arr+10

In [158]:
print(arr+10)# broadcasting

[[11 12 13 14]
 [15 16 17 18]
 [18 17 16 15]
 [14 13 12 11]]


In [161]:
arr1

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [18, 17, 16, 15],
       [14, 13, 12, 11]])

In [163]:
a

array([[1],
       [2],
       [3]])

In [164]:
b

array([10, 20, 30])

In [162]:
a = np.array([[1],[2],[3]])
b = np.array([10,20,30])

print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [165]:
a*b

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [166]:
a*10

array([[10],
       [20],
       [30]])

- > Aggregation Methods:
  - 1.sum()
  - 2.max()
  - 3.min()
  - 4.mean()
  - 5.median()
  - 6.std()

In [131]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [8 7 6 5]
 [4 3 2 1]]


In [132]:
print(arr.sum())

print(arr.max())

print(arr.min())

print(arr.mean())

#print(arr.median(arr)) # its not the right way

print(np.median(arr))

print(arr.std())

72
8
1
4.5
4.5
2.29128784747792


In [168]:
arr = np.array([[1,2,3],[5,6,7]])
print(arr)

print(np.sum(arr,axis=0)) #column wise addition

print(np.sum(arr,axis=1)) # row wise addition


print(np.sum(arr))

[[1 2 3]
 [5 6 7]]
[ 6  8 10]
[ 6 18]
24


### universal functions

- 1.log
- 2.sqrt
- 3.exp
- 4.sin..

In [128]:
arr = np.array([[8,9,36],[5,81,7]])
print(arr)


# print(np.log(arr))
# print(np.sqrt(arr))
# print(np.exp(arr))
# print(np.sin(arr))

[[ 8  9 36]
 [ 5 81  7]]


In [129]:
arr = np.array([[8,9,36],[5,6,7]])
print(arr)

# masking

mask = arr>20
print(mask)

[[ 8  9 36]
 [ 5  6  7]]
[[False False  True]
 [False False False]]


In [ ]:
arr = np.array([[8,9,36],[5,6,72]])
print(arr)

res = arr[(arr >10)&(arr % 2==0)] #filtering.
print(res)

In [ ]:
arr = np.array([8,9,36,5,6,7])
# print(arr)

print(np.sort(arr)) # 1d sorting.

In [ ]:


print(np.argsort(arr))
print(np.argsort(arr[::-1]))

In [ ]:
arr = np.array([8,9,36,5,6,7])
arr1 = np.array([12,3,4,5,6])

print(np.concatenate([arr,arr1]))

In [ ]:
arr = np.array([8,9,36])
arr1 = np.array([12,3,4])

np.vstack((arr,arr1))